version: '3.8'  # Specify the version of Docker Compose

services:
  postgres:
    image: postgres:latest
    container_name: 40krusadeDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: prycebear
      POSTGRES_PASSWORD: Ashashcat1
      POSTGRES_DB: 40krusadeDB
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  # This volume will store the database data


# -----------------------------
# Commands to start and stop
# -----------------------------
# To start the containers:
# docker-compose up -d
# This will start the container in detached mode (running in the background).

# To stop the containers:
# docker-compose down
# This stops and removes the containers, networks, and volumes defined in the docker-compose file.
# You can also use `docker-compose stop` to stop containers but leave them in place.