spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/40krusadeDB
    username: prycebear
    password: Ashashcat1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: prycebear  # Change this to the desired username
      password: Ashashcat1  # Change this to the desired password
server:
  address: 0.0.0.0
  port: 8080